# Generated by Django 4.2.3 on 2023-07-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoaddress',
            name='currency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('DOGE', 'Dogecoin'), ('LTC', 'Litecoin'), ('TRX', 'TRON')], max_length=4),
        ),
    ]
